// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VitekSky.Data;

namespace VitekSky.Migrations
{
    [DbContext(typeof(BusinessContext))]
    [Migration("20191117161505_RowVersion")]
    partial class RowVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VitekSky.Models.CountryAssignment", b =>
                {
                    b.Property<int>("ProductGuideID");

                    b.Property<string>("Location")
                        .HasMaxLength(50);

                    b.HasKey("ProductGuideID");

                    b.ToTable("CountryAssignment");
                });

            modelBuilder.Entity("VitekSky.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasColumnName("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("SubscriptionDate");

                    b.HasKey("ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("VitekSky.Models.Market", b =>
                {
                    b.Property<int>("MarketID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Budget")
                        .HasColumnType("money");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("ProductGuideID");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("StartDate");

                    b.HasKey("MarketID");

                    b.HasIndex("ProductGuideID");

                    b.ToTable("Market");
                });

            modelBuilder.Entity("VitekSky.Models.Product", b =>
                {
                    b.Property<int>("ProductID");

                    b.Property<int>("MarketID");

                    b.Property<int>("Price");

                    b.Property<string>("ProductName")
                        .HasMaxLength(50);

                    b.HasKey("ProductID");

                    b.HasIndex("MarketID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("VitekSky.Models.ProductAssignment", b =>
                {
                    b.Property<int>("ProductID");

                    b.Property<int>("ProductGuideID");

                    b.HasKey("ProductID", "ProductGuideID");

                    b.HasIndex("ProductGuideID");

                    b.ToTable("ProductAssignment");
                });

            modelBuilder.Entity("VitekSky.Models.ProductGuide", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasColumnName("FirstName")
                        .HasMaxLength(50);

                    b.Property<DateTime>("HireDate");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("ProductGuide");
                });

            modelBuilder.Entity("VitekSky.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerID");

                    b.Property<int?>("CustomerLoyalty");

                    b.Property<int>("ProductID");

                    b.HasKey("SubscriptionID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProductID");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("VitekSky.Models.CountryAssignment", b =>
                {
                    b.HasOne("VitekSky.Models.ProductGuide", "ProductGuide")
                        .WithOne("CountryAssignment")
                        .HasForeignKey("VitekSky.Models.CountryAssignment", "ProductGuideID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VitekSky.Models.Market", b =>
                {
                    b.HasOne("VitekSky.Models.ProductGuide", "Administrator")
                        .WithMany()
                        .HasForeignKey("ProductGuideID");
                });

            modelBuilder.Entity("VitekSky.Models.Product", b =>
                {
                    b.HasOne("VitekSky.Models.Market", "Market")
                        .WithMany("Products")
                        .HasForeignKey("MarketID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VitekSky.Models.ProductAssignment", b =>
                {
                    b.HasOne("VitekSky.Models.ProductGuide", "ProductGuide")
                        .WithMany("ProductAssignments")
                        .HasForeignKey("ProductGuideID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VitekSky.Models.Product", "Product")
                        .WithMany("ProductAssignments")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VitekSky.Models.Subscription", b =>
                {
                    b.HasOne("VitekSky.Models.Customer", "Customer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VitekSky.Models.Product", "Product")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
